/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Dec 12 23:29:44 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void BBB_Quaternion_SFRotation_Outputs_wrapper(const real_T *inQuat_q_1,
                          const real_T *inQuat_q_2,
                          const real_T *inQuat_q_3,
                          const real_T *inQuat_q_4,
                          real_T *outSFRot_r_1,
                          real_T *outSFRot_r_2,
                          real_T *outSFRot_r_3,
                          real_T *outSFRot_r_4)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
// Declare Temporary Holder Variables
double dSFRot_r_1=0;
double dSFRot_r_2=0;
double dSFRot_r_3=0;
double dSFRot_r_4=0;
double dSFRot_Angle=0;


// Calculate Output Data

// Rotation Angle
dSFRot_Angle=2*acos(inQuat_q_1[0]);

if (dSFRot_Angle!=0)
{
  dSFRot_r_1=inQuat_q_2[0]/sin(dSFRot_Angle/2);  
  dSFRot_r_2=inQuat_q_3[0]/sin(dSFRot_Angle/2); 
  dSFRot_r_3=inQuat_q_4[0]/sin(dSFRot_Angle/2);
}
else
{
  dSFRot_r_1=0;  
  dSFRot_r_2=0; 
  dSFRot_r_3=0;
}

// Set Output Data 
// Correct for +Y at Aircaft Head!
outSFRot_r_1[0]=-dSFRot_r_1;
outSFRot_r_2[0]=-dSFRot_r_3;
outSFRot_r_3[0]=dSFRot_r_2;
outSFRot_r_4[0]=dSFRot_Angle;


// Correct for -Y at Aircaft Head!
// outSFRot_r_1[0]=-dSFRot_r_1;
// outSFRot_r_2[0]=dSFRot_r_3;
// outSFRot_r_3[0]=dSFRot_r_2;
// outSFRot_r_4[0]=-dSFRot_Angle;


// Correct for +Y at Aircaft Head!
// outSFRot_r_1[0]=-dSFRot_r_1;
// outSFRot_r_2[0]=-dSFRot_r_3;
// outSFRot_r_3[0]=dSFRot_r_2;
// outSFRot_r_4[0]=dSFRot_Angle;
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
