/*
 * File: BBB_Driver_Compass_HMC5883L.c
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Sun Dec 14 05:08:04 2014
 * 
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME BBB_Driver_Compass_HMC5883L
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS           0

#define NUM_OUTPUTS          6
/* Output Port  0 */
#define OUT_PORT_0_NAME      outMagField_HX
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       real_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME      outMagField_HY
#define OUTPUT_1_WIDTH       1
#define OUTPUT_DIMS_1_COL    1
#define OUTPUT_1_DTYPE       real_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_BUS_BASED      0
#define OUT_1_BUS_NAME       
#define OUT_1_DIMS           1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME      outMagField_HZ
#define OUTPUT_2_WIDTH       1
#define OUTPUT_DIMS_2_COL    1
#define OUTPUT_2_DTYPE       real_T
#define OUTPUT_2_COMPLEX     COMPLEX_NO
#define OUT_2_FRAME_BASED    FRAME_NO
#define OUT_2_BUS_BASED      0
#define OUT_2_BUS_NAME       
#define OUT_2_DIMS           1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME      outMagField_HE
#define OUTPUT_3_WIDTH       1
#define OUTPUT_DIMS_3_COL    1
#define OUTPUT_3_DTYPE       real_T
#define OUTPUT_3_COMPLEX     COMPLEX_NO
#define OUT_3_FRAME_BASED    FRAME_NO
#define OUT_3_BUS_BASED      0
#define OUT_3_BUS_NAME       
#define OUT_3_DIMS           1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125
/* Output Port  4 */
#define OUT_PORT_4_NAME      outMagField_Heading
#define OUTPUT_4_WIDTH       1
#define OUTPUT_DIMS_4_COL    1
#define OUTPUT_4_DTYPE       real_T
#define OUTPUT_4_COMPLEX     COMPLEX_NO
#define OUT_4_FRAME_BASED    FRAME_NO
#define OUT_4_BUS_BASED      0
#define OUT_4_BUS_NAME       
#define OUT_4_DIMS           1-D
#define OUT_4_ISSIGNED        1
#define OUT_4_WORDLENGTH      8
#define OUT_4_FIXPOINTSCALING 1
#define OUT_4_FRACTIONLENGTH  3
#define OUT_4_BIAS            0
#define OUT_4_SLOPE           0.125
/* Output Port  5 */
#define OUT_PORT_5_NAME      outSimStop
#define OUTPUT_5_WIDTH       1
#define OUTPUT_DIMS_5_COL    1
#define OUTPUT_5_DTYPE       real_T
#define OUTPUT_5_COMPLEX     COMPLEX_NO
#define OUT_5_FRAME_BASED    FRAME_NO
#define OUT_5_BUS_BASED      0
#define OUT_5_BUS_NAME       
#define OUT_5_DIMS           1-D
#define OUT_5_ISSIGNED        1
#define OUT_5_WORDLENGTH      8
#define OUT_5_FIXPOINTSCALING 1
#define OUT_5_FRACTIONLENGTH  3
#define OUT_5_BIAS            0
#define OUT_5_SLOPE           0.125

#define NPARAMS              13
/* Parameter  1 */
#define PARAMETER_0_NAME      prmI2C_DeviceNo
#define PARAMETER_0_DTYPE     uint8_T
#define PARAMETER_0_COMPLEX   COMPLEX_NO
/* Parameter  2 */
#define PARAMETER_1_NAME      prmI2C_BusNo
#define PARAMETER_1_DTYPE     uint8_T
#define PARAMETER_1_COMPLEX   COMPLEX_NO
/* Parameter  3 */
#define PARAMETER_2_NAME      prmCompass_DataOutAvrg
#define PARAMETER_2_DTYPE     uint8_T
#define PARAMETER_2_COMPLEX   COMPLEX_NO
/* Parameter  4 */
#define PARAMETER_3_NAME      prmCompass_DataOutRate
#define PARAMETER_3_DTYPE     uint8_T
#define PARAMETER_3_COMPLEX   COMPLEX_NO
/* Parameter  5 */
#define PARAMETER_4_NAME      prmCompass_MeasureMode
#define PARAMETER_4_DTYPE     uint8_T
#define PARAMETER_4_COMPLEX   COMPLEX_NO
/* Parameter  6 */
#define PARAMETER_5_NAME      prmCompass_GainValue
#define PARAMETER_5_DTYPE     uint8_T
#define PARAMETER_5_COMPLEX   COMPLEX_NO
/* Parameter  7 */
#define PARAMETER_6_NAME      prmCompass_OpMode
#define PARAMETER_6_DTYPE     uint8_T
#define PARAMETER_6_COMPLEX   COMPLEX_NO
/* Parameter  8 */
#define PARAMETER_7_NAME      prmCompass_HeadingMode
#define PARAMETER_7_DTYPE     uint8_T
#define PARAMETER_7_COMPLEX   COMPLEX_NO
/* Parameter  9 */
#define PARAMETER_8_NAME      prmCompass_HeadingOffset
#define PARAMETER_8_DTYPE     real_T
#define PARAMETER_8_COMPLEX   COMPLEX_NO
/* Parameter  10 */
#define PARAMETER_9_NAME      prmCompass_DeclinationAng
#define PARAMETER_9_DTYPE     real_T
#define PARAMETER_9_COMPLEX   COMPLEX_NO
/* Parameter  11 */
#define PARAMETER_10_NAME      prmCompass_SelfTest
#define PARAMETER_10_DTYPE     boolean_T
#define PARAMETER_10_COMPLEX   COMPLEX_NO
/* Parameter  12 */
#define PARAMETER_11_NAME      prmCompass_SelfTest_GainValue
#define PARAMETER_11_DTYPE     uint8_T
#define PARAMETER_11_COMPLEX   COMPLEX_NO
/* Parameter  13 */
#define PARAMETER_12_NAME      prmDebug_InfoLevel
#define PARAMETER_12_DTYPE     uint8_T
#define PARAMETER_12_COMPLEX   COMPLEX_NO

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      2
#define DISC_STATES_IC       [0,0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S) ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S) ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S) ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S) ssGetSFcnParam(S, 4)
#define PARAM_DEF5(S) ssGetSFcnParam(S, 5)
#define PARAM_DEF6(S) ssGetSFcnParam(S, 6)
#define PARAM_DEF7(S) ssGetSFcnParam(S, 7)
#define PARAM_DEF8(S) ssGetSFcnParam(S, 8)
#define PARAM_DEF9(S) ssGetSFcnParam(S, 9)
#define PARAM_DEF10(S) ssGetSFcnParam(S, 10)
#define PARAM_DEF11(S) ssGetSFcnParam(S, 11)
#define PARAM_DEF12(S) ssGetSFcnParam(S, 12)

#define IS_PARAM_UINT8(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsUint8(pVal))

#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

#define IS_PARAM_BOOLEAN(pVal) (mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal))

extern void BBB_Driver_Compass_HMC5883L_Outputs_wrapper(real_T *outMagField_HX,
                          real_T *outMagField_HY,
                          real_T *outMagField_HZ,
                          real_T *outMagField_HE,
                          real_T *outMagField_Heading,
                          real_T *outSimStop ,
			      const real_T  *xD,
                          const uint8_T  *prmI2C_DeviceNo, const int_T  p_width0, 
                          const uint8_T  *prmI2C_BusNo, const int_T  p_width1, 
                          const uint8_T  *prmCompass_DataOutAvrg, const int_T  p_width2, 
                          const uint8_T  *prmCompass_DataOutRate, const int_T  p_width3, 
                          const uint8_T  *prmCompass_MeasureMode, const int_T  p_width4, 
                          const uint8_T  *prmCompass_GainValue, const int_T  p_width5, 
                          const uint8_T  *prmCompass_OpMode, const int_T  p_width6, 
                          const uint8_T  *prmCompass_HeadingMode, const int_T  p_width7, 
                          const real_T  *prmCompass_HeadingOffset, const int_T  p_width8, 
                          const real_T  *prmCompass_DeclinationAng, const int_T  p_width9, 
                          const boolean_T  *prmCompass_SelfTest, const int_T  p_width10, 
                          const uint8_T  *prmCompass_SelfTest_GainValue, const int_T  p_width11, 
                          const uint8_T  *prmDebug_InfoLevel, const int_T p_width12);
extern void BBB_Driver_Compass_HMC5883L_Update_wrapper(const real_T *outMagField_HX,
                          const real_T *outMagField_HY,
                          const real_T *outMagField_HZ,
                          const real_T *outMagField_HE,
                          const real_T *outMagField_Heading,
                          const real_T *outSimStop ,
                          real_T *xD, 
                          const uint8_T  *prmI2C_DeviceNo,  const int_T  p_width0,
                          const uint8_T  *prmI2C_BusNo,  const int_T  p_width1,
                          const uint8_T  *prmCompass_DataOutAvrg,  const int_T  p_width2,
                          const uint8_T  *prmCompass_DataOutRate,  const int_T  p_width3,
                          const uint8_T  *prmCompass_MeasureMode,  const int_T  p_width4,
                          const uint8_T  *prmCompass_GainValue,  const int_T  p_width5,
                          const uint8_T  *prmCompass_OpMode,  const int_T  p_width6,
                          const uint8_T  *prmCompass_HeadingMode,  const int_T  p_width7,
                          const real_T  *prmCompass_HeadingOffset,  const int_T  p_width8,
                          const real_T  *prmCompass_DeclinationAng,  const int_T  p_width9,
                          const boolean_T  *prmCompass_SelfTest,  const int_T  p_width10,
                          const uint8_T  *prmCompass_SelfTest_GainValue,  const int_T  p_width11,
                           const uint8_T *prmDebug_InfoLevel, const int_T  p_width12);

/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
 #if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
   /* Function: mdlCheckParameters =============================================
     * Abstract:
     *    Validate our parameters to verify they are okay.
     */
    static void mdlCheckParameters(SimStruct *S)
    {
     int paramIndex  = 0;
     bool validParam = false;
     /* All parameters must match the S-function Builder Dialog */
     

	 {
	  const mxArray *pVal0 = ssGetSFcnParam(S,0);
	  if (!IS_PARAM_UINT8(pVal0)) {
	    validParam = true;
	    paramIndex = 0;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal1 = ssGetSFcnParam(S,1);
	  if (!IS_PARAM_UINT8(pVal1)) {
	    validParam = true;
	    paramIndex = 1;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal2 = ssGetSFcnParam(S,2);
	  if (!IS_PARAM_UINT8(pVal2)) {
	    validParam = true;
	    paramIndex = 2;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal3 = ssGetSFcnParam(S,3);
	  if (!IS_PARAM_UINT8(pVal3)) {
	    validParam = true;
	    paramIndex = 3;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal4 = ssGetSFcnParam(S,4);
	  if (!IS_PARAM_UINT8(pVal4)) {
	    validParam = true;
	    paramIndex = 4;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal5 = ssGetSFcnParam(S,5);
	  if (!IS_PARAM_UINT8(pVal5)) {
	    validParam = true;
	    paramIndex = 5;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal6 = ssGetSFcnParam(S,6);
	  if (!IS_PARAM_UINT8(pVal6)) {
	    validParam = true;
	    paramIndex = 6;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal7 = ssGetSFcnParam(S,7);
	  if (!IS_PARAM_UINT8(pVal7)) {
	    validParam = true;
	    paramIndex = 7;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal8 = ssGetSFcnParam(S,8);
	  if (!IS_PARAM_DOUBLE(pVal8)) {
	    validParam = true;
	    paramIndex = 8;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal9 = ssGetSFcnParam(S,9);
	  if (!IS_PARAM_DOUBLE(pVal9)) {
	    validParam = true;
	    paramIndex = 9;
	    goto EXIT_POINT;
	  }
	 }
	 {
	  const mxArray *pVal10 = ssGetSFcnParam(S,10);
	  if (!IS_PARAM_BOOLEAN(pVal10)) {
	    validParam = true;
	    paramIndex = 10;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal11 = ssGetSFcnParam(S,11);
	  if (!IS_PARAM_UINT8(pVal11)) {
	    validParam = true;
	    paramIndex = 11;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal12 = ssGetSFcnParam(S,12);
	  if (!IS_PARAM_UINT8(pVal12)) {
	    validParam = true;
	    paramIndex = 12;
	    goto EXIT_POINT;
	  }
	 }
      
     EXIT_POINT:
      if (validParam) {
          char parameterErrorMsg[1024];
          sprintf(parameterErrorMsg, "The data type and or complexity of parameter  %d does not match the "
                  "information specified in the S-function Builder dialog. "
                  "For non-double parameters you will need to cast them using int8, int16, "
                  "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
	  ssSetErrorStatus(S,parameterErrorMsg);
      }
	return;
    }
 #endif /* MDL_CHECK_PARAMETERS */
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);  /* Number of expected parameters */
      #if defined(MATLAB_MEX_FILE)
	if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
	  mdlCheckParameters(S);
	  if (ssGetErrorStatus(S) != NULL) {
	    return;
	  }
	 } else {
	   return; /* Parameter mismatch will be reported by Simulink */
	 }
      #endif

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);
    /* Output Port 4 */
    ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
    ssSetOutputPortDataType(S, 4, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);
    /* Output Port 5 */
    ssSetOutputPortWidth(S, 5, OUTPUT_5_WIDTH);
    ssSetOutputPortDataType(S, 5, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR | 
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}
#define MDL_INITIALIZE_CONDITIONS
 /* Function: mdlInitializeConditions ========================================
  * Abstract:
  *    Initialize the states
  */
 static void mdlInitializeConditions(SimStruct *S)
 {
   real_T *xD   = ssGetRealDiscStates(S);
   
    
    xD[0] =  0;
    xD[1] =  0;
    
 }
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
   ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    real_T        *outMagField_HX  = (real_T *)ssGetOutputPortRealSignal(S,0);
    real_T        *outMagField_HY  = (real_T *)ssGetOutputPortRealSignal(S,1);
    real_T        *outMagField_HZ  = (real_T *)ssGetOutputPortRealSignal(S,2);
    real_T        *outMagField_HE  = (real_T *)ssGetOutputPortRealSignal(S,3);
    real_T        *outMagField_Heading  = (real_T *)ssGetOutputPortRealSignal(S,4);
    real_T        *outSimStop  = (real_T *)ssGetOutputPortRealSignal(S,5);
    const real_T   *xD = ssGetDiscStates(S);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
    const int_T   p_width4  = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width5  = mxGetNumberOfElements(PARAM_DEF5(S));
    const int_T   p_width6  = mxGetNumberOfElements(PARAM_DEF6(S));
    const int_T   p_width7  = mxGetNumberOfElements(PARAM_DEF7(S));
    const int_T   p_width8  = mxGetNumberOfElements(PARAM_DEF8(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));
    const int_T   p_width10  = mxGetNumberOfElements(PARAM_DEF10(S));
    const int_T   p_width11  = mxGetNumberOfElements(PARAM_DEF11(S));
    const int_T   p_width12  = mxGetNumberOfElements(PARAM_DEF12(S));
    const uint8_T  *prmI2C_DeviceNo  = (const uint8_T *)mxGetData(PARAM_DEF0(S));
    const uint8_T  *prmI2C_BusNo  = (const uint8_T *)mxGetData(PARAM_DEF1(S));
    const uint8_T  *prmCompass_DataOutAvrg  = (const uint8_T *)mxGetData(PARAM_DEF2(S));
    const uint8_T  *prmCompass_DataOutRate  = (const uint8_T *)mxGetData(PARAM_DEF3(S));
    const uint8_T  *prmCompass_MeasureMode  = (const uint8_T *)mxGetData(PARAM_DEF4(S));
    const uint8_T  *prmCompass_GainValue  = (const uint8_T *)mxGetData(PARAM_DEF5(S));
    const uint8_T  *prmCompass_OpMode  = (const uint8_T *)mxGetData(PARAM_DEF6(S));
    const uint8_T  *prmCompass_HeadingMode  = (const uint8_T *)mxGetData(PARAM_DEF7(S));
    const real_T  *prmCompass_HeadingOffset  = (const real_T *)mxGetData(PARAM_DEF8(S));
    const real_T  *prmCompass_DeclinationAng  = (const real_T *)mxGetData(PARAM_DEF9(S));
    const boolean_T  *prmCompass_SelfTest  = (const boolean_T *)mxGetData(PARAM_DEF10(S));
    const uint8_T  *prmCompass_SelfTest_GainValue  = (const uint8_T *)mxGetData(PARAM_DEF11(S));
    const uint8_T  *prmDebug_InfoLevel  = (const uint8_T *)mxGetData(PARAM_DEF12(S));

    BBB_Driver_Compass_HMC5883L_Outputs_wrapper(outMagField_HX, outMagField_HY, outMagField_HZ, outMagField_HE, outMagField_Heading, outSimStop, xD, prmI2C_DeviceNo, p_width0, prmI2C_BusNo, p_width1, prmCompass_DataOutAvrg, p_width2, prmCompass_DataOutRate, p_width3, prmCompass_MeasureMode, p_width4, prmCompass_GainValue, p_width5, prmCompass_OpMode, p_width6, prmCompass_HeadingMode, p_width7, prmCompass_HeadingOffset, p_width8, prmCompass_DeclinationAng, p_width9, prmCompass_SelfTest, p_width10, prmCompass_SelfTest_GainValue, p_width11, prmDebug_InfoLevel, p_width12);
}
#define MDL_UPDATE  /* Change to #undef to remove function */
/* Function: mdlUpdate ======================================================
   * Abstract:
   *    This function is called once for every major integration time step.
   *    Discrete states are typically updated here, but this function is useful
   *    for performing any tasks that should only take place once per
   *    integration step.
   */
  static void mdlUpdate(SimStruct *S, int_T tid)
  {
    real_T         *xD  = ssGetDiscStates(S);
    real_T        *outMagField_HX  = (real_T *)ssGetOutputPortRealSignal(S,0);
    real_T        *outMagField_HY  = (real_T *)ssGetOutputPortRealSignal(S,1);
    real_T        *outMagField_HZ  = (real_T *)ssGetOutputPortRealSignal(S,2);
    real_T        *outMagField_HE  = (real_T *)ssGetOutputPortRealSignal(S,3);
    real_T        *outMagField_Heading  = (real_T *)ssGetOutputPortRealSignal(S,4);
    real_T        *outSimStop  = (real_T *)ssGetOutputPortRealSignal(S,5);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
    const int_T   p_width4  = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width5  = mxGetNumberOfElements(PARAM_DEF5(S));
    const int_T   p_width6  = mxGetNumberOfElements(PARAM_DEF6(S));
    const int_T   p_width7  = mxGetNumberOfElements(PARAM_DEF7(S));
    const int_T   p_width8  = mxGetNumberOfElements(PARAM_DEF8(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));
    const int_T   p_width10  = mxGetNumberOfElements(PARAM_DEF10(S));
    const int_T   p_width11  = mxGetNumberOfElements(PARAM_DEF11(S));
    const int_T   p_width12  = mxGetNumberOfElements(PARAM_DEF12(S));
    const uint8_T  *prmI2C_DeviceNo  = (const uint8_T *)mxGetData(PARAM_DEF0(S));
    const uint8_T  *prmI2C_BusNo  = (const uint8_T *)mxGetData(PARAM_DEF1(S));
    const uint8_T  *prmCompass_DataOutAvrg  = (const uint8_T *)mxGetData(PARAM_DEF2(S));
    const uint8_T  *prmCompass_DataOutRate  = (const uint8_T *)mxGetData(PARAM_DEF3(S));
    const uint8_T  *prmCompass_MeasureMode  = (const uint8_T *)mxGetData(PARAM_DEF4(S));
    const uint8_T  *prmCompass_GainValue  = (const uint8_T *)mxGetData(PARAM_DEF5(S));
    const uint8_T  *prmCompass_OpMode  = (const uint8_T *)mxGetData(PARAM_DEF6(S));
    const uint8_T  *prmCompass_HeadingMode  = (const uint8_T *)mxGetData(PARAM_DEF7(S));
    const real_T  *prmCompass_HeadingOffset  = (const real_T *)mxGetData(PARAM_DEF8(S));
    const real_T  *prmCompass_DeclinationAng  = (const real_T *)mxGetData(PARAM_DEF9(S));
    const boolean_T  *prmCompass_SelfTest  = (const boolean_T *)mxGetData(PARAM_DEF10(S));
    const uint8_T  *prmCompass_SelfTest_GainValue  = (const uint8_T *)mxGetData(PARAM_DEF11(S));
    const uint8_T  *prmDebug_InfoLevel  = (const uint8_T *)mxGetData(PARAM_DEF12(S));

    BBB_Driver_Compass_HMC5883L_Update_wrapper(outMagField_HX, outMagField_HY, outMagField_HZ, outMagField_HE, outMagField_Heading, outSimStop,  xD, prmI2C_DeviceNo, p_width0, prmI2C_BusNo, p_width1, prmCompass_DataOutAvrg, p_width2, prmCompass_DataOutRate, p_width3, prmCompass_MeasureMode, p_width4, prmCompass_GainValue, p_width5, prmCompass_OpMode, p_width6, prmCompass_HeadingMode, p_width7, prmCompass_HeadingOffset, p_width8, prmCompass_DeclinationAng, p_width9, prmCompass_SelfTest, p_width10, prmCompass_SelfTest_GainValue, p_width11, prmDebug_InfoLevel, p_width12);
}


/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}
#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


