/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Tue Aug 12 21:06:14 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include <stdio.h>
#include <stddef.h>
#include <time.h>

# ifdef MATLAB_MEX_FILE
	#include <mex.h>
	#include <simstruc.h>
# endif
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void BBB_Driver_Accelerometer_ADXL330_TSR2_Outputs_wrapper(real_T *X_Axis_Accel,
                          real_T *Y_Axis_Accel,
                          real_T *Z_Axis_Accel)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
// Define Output Data - Simulink

// Run Only on Target - BeagleBoneBlack */
# ifndef MATLAB_MEX_FILE

// Define File Sys Pointer
static FILE *BBB_Handle_X = NULL;
static FILE *BBB_Handle_Y = NULL;
static FILE *BBB_Handle_Z = NULL;
const char *BBB_ACC_AIN_X ="/sys/bus/platform/drivers/bone-iio-helper/helper.15/AIN0";
const char *BBB_ACC_AIN_Y ="/sys/bus/platform/drivers/bone-iio-helper/helper.15/AIN1";
const char *BBB_ACC_AIN_Z ="/sys/bus/platform/drivers/bone-iio-helper/helper.15/AIN2";

// Define Internal Variables Data
float BBB_ADC_Volt_Val_X;
float BBB_ADC_Volt_Val_Y;
float BBB_ADC_Volt_Val_Z;
float BBB_ACC_Val_X;
float BBB_ACC_Val_Y;
float BBB_ACC_Val_Z;
float const BBB_ACC_Val_X_Nominal=1666+(-0.06006*333);
float const BBB_ACC_Val_Y_Nominal=1666+(-1.234234*333);//+(-0.234234*333);
float const BBB_ACC_Val_Z_Nominal=1666+((0.912013-1)*333);


// Open Streams
        
        BBB_Handle_X = fopen(BBB_ACC_AIN_X, "r");
        BBB_Handle_Y = fopen(BBB_ACC_AIN_Y, "r");
        BBB_Handle_Z = fopen(BBB_ACC_AIN_Z, "r");

        // Read X Accel
        fseek(BBB_Handle_X, 0, SEEK_SET);
        fscanf(BBB_Handle_X, "%f", &BBB_ADC_Volt_Val_X);
        // Read Y Accel
        fseek(BBB_Handle_Y, 0, SEEK_SET);
        fscanf(BBB_Handle_Y, "%f", &BBB_ADC_Volt_Val_Y);
        // Read Z Accel
        fseek(BBB_Handle_Z, 0, SEEK_SET);
        fscanf(BBB_Handle_Z, "%f", &BBB_ADC_Volt_Val_Z);        
       
        // Convert Voltage To Acceleration (in g) - 3.33 VDD
        BBB_ACC_Val_X=((2*BBB_ADC_Volt_Val_X)-BBB_ACC_Val_X_Nominal)/333;
        BBB_ACC_Val_Y=((2*BBB_ADC_Volt_Val_Y)-BBB_ACC_Val_Y_Nominal)/333;
        BBB_ACC_Val_Z=((2*BBB_ADC_Volt_Val_Z)-BBB_ACC_Val_Z_Nominal)/333;
      
        // Close File on Exit
        fclose(BBB_Handle_X);
        fclose(BBB_Handle_Y);
        fclose(BBB_Handle_Z);

        // Print Acceleration Data 
         printf("Accel: X: %f  Y: %f  Z: %f\n",BBB_ACC_Val_X,BBB_ACC_Val_Y,BBB_ACC_Val_Z);
        // Print Voltage Data
        //printf("Voltage: X: %f  Y: %f  Z: %f\n",BBB_ADC_Volt_Val_X,BBB_ADC_Volt_Val_Y,BBB_ADC_Volt_Val_Z);
        
        // Check Transfer to S-Block Output
        // printf("Accel S-Out: X: %f  Y: %f  Z: %f\n",X_Axis_Accel[0],Y_Axis_Accel[0],Z_Axis_Accel[0]);
         
        // Transfer Data to Outputs!
        X_Axis_Accel[0]=BBB_ACC_Val_X;
        Y_Axis_Accel[0]=BBB_ACC_Val_Y;
        Z_Axis_Accel[0]=BBB_ACC_Val_Z;
      
        // Test Print Functionality
        //ssPrintf("Accel: X: %f  Y: %f  Z: %f\n",BBB_ACC_Val_X_SLink,BBB_ACC_Val_Y_SLink,BBB_ACC_Val_Z_SLink);
        //mexPrintf("Accel: X: %f  Y: %f  Z: %f\n",BBB_ACC_Val_X_SLink,BBB_ACC_Val_Y_SLink,BBB_ACC_Val_Z_SLink);
 
    
# else
        
   // Output to Matlab  Command Promt (Not Working)
    // Print Acceleration Data 
    //ssPrintf("Accel: X: %f  Y: %f  Z: %f\n",BBB_ACC_Val_X_SLink,BBB_ACC_Val_Y_SLink,BBB_ACC_Val_Z_SLink);
    //mexPrintf("Accel: X: %f  Y: %f  Z: %f\n",BBB_ACC_Val_X_SLink,BBB_ACC_Val_Y_SLink,BBB_ACC_Val_Z_SLink);
    // Check S-Function Output
    ssPrintf("Output Accel: %f %f %f\n",X_Axis_Accel[0],Y_Axis_Accel[0],Z_Axis_Accel[0]);
    mexPrintf("Inter  Accel: %f %f %f\n",X_Axis_Accel[0],Y_Axis_Accel[0],Z_Axis_Accel[0]);
    ssPrintf("Hello World 1 !");
    mexPrintf("Hello World 2 !");
   
# endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
