/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sun Dec 14 05:03:39 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>

/* Include only when running on target hardware */
# ifndef MATLAB_MEX_FILE
	/* #include <iostream.h> */
	#include <stdio.h>
	#include <unistd.h>
	#include <string.h>
# endif


#define MAX_BUF 100


typedef enum 
{
    BBB_USRLED0=1,
	BBB_USRLED1=2,
    BBB_USRLED2=3,
	BBB_USRLED3=4,
}eUSRLED_LEDID;

typedef enum 
{
       	BBB_USRLED_OFF=0,
	BBB_USRLED_ON=1
}eUSRLED_STATE;

// Define Debug Levels
typedef enum 
{
       	Debug_None,
	Debug_Level_0, // Basic Debug Info Output
    Debug_Level_1, // + Critical Info Only
	Debug_Level_2, // + Diagnostics Info
	Debug_Level_3, // + Program Flow Info
	Debug_Level_4, // + Registry Data
	Debug_Level_5  // + TBD 
}eDebugLevel;


// Define Error Number
typedef enum 
{
    Error_None=0,
    Error_No_SYSFSOpen,
    Error_No_SYSFSRead,
    Error_No_SYSFSWrite,
    Error_No_ParamOutofRange,
    Error_No_USRLED_TriggerOn, 
    Error_No_USRLED_TriggerOff
}eError_No;

// Initialize Error
// eError_No iError_No = Error_None;

// Define Error Severity Levels
typedef enum
{
    Error_Level_OK=0,
    Error_Level_Critical, // (Stop Simulation)
    Error_Level_Warning
}eError_Level;
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */

const char *sSYSFSReadWrite_ErrMessage(eError_No iErrNo)
{
    //Set Error Message Based on Error Number
    switch(iErrNo)
    {     
       case  Error_None:
            return("No Error Active. System A-OK!\n");
            break;
        case  Error_No_SYSFSOpen: 
            return("Failed to Open I2C Bus\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device\n - Check Device Tree on BBB\n");
            break;
        case Error_No_SYSFSRead:
            return("Failed to Communicate With Slave Device\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device Address\n - Check Device Tree on BBB\n");        
            break;            
        case Error_No_SYSFSWrite:
            return("Failed to Set Buffer Read Range\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device Address\n - Check Device Tree on BBB\n");            
            break;
        case Error_No_USRLED_TriggerOn:
            return("Failed to Read Data in Registry Buffer\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device Address\n - Check Device Tree on BBB\n");
            break;
        case Error_No_USRLED_TriggerOff:
            return("Failed to Validate Registry Data - Inconsistent Data Stream\n"
                    " - Check For Multiple Master Access to Slave Device on I2C Bus Number\n"
                    " - Check SCL/SCA Lines\n - Check Device Address\n - Check Device Tree on BBB\n");
            break;                
        case Error_No_ParamOutofRange:
            return("Parameter Out Of Range\n - Check Block Parameter Input Options\n");
            break;        
        default:
            // Error -Return Default 
            return("Error Code Not Recognized\n");
            break;
                    
 
    }
}
// Set Debug Level
int iSet_Debug_Level(eDebugLevel iDebug_Level_X)
{

    switch(iDebug_Level_X)
    {
        case  1:
            return (Debug_None);
            break;
        case  2:
            return (Debug_Level_0);
            break;
        case  3:
            return (Debug_Level_1);
            break;
        case  4:
            return (Debug_Level_2);
            break;
        case  5:
            return (Debug_Level_3);
            break;
        case  6:
            return (Debug_Level_4);
            break;
        case  7:
            return (Debug_Level_5);
            break;
        default:
            return (Debug_None);
            break;
    }
}
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void BBB_Driver_USRLED_Outputs_wrapper(const real_T *inUSRLED_Enable,
                          const boolean_T *inUSRLED_On_Trigger,
                          boolean_T *outUSRLED_State,
                          boolean_T *outSimStop ,
			      const real_T  *xD,
                          const uint8_T  *prmUSRLED_No, const int_T  p_width0, 
                          const uint8_T  *prmDebug_InfoLevel, const int_T p_width1)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* Run only on target - BeagleBoneBlack */
# ifndef MATLAB_MEX_FILE

static FILE *iFILE_BBB_USRLED_Handle = NULL;
const char *sSYSFS_USRLED="/sys/class/leds/beaglebone:green:usr";
char sSYSFS_USRLED_Brightness[MAX_BUF]="";
char sSYSFS_USRLED_Trigger[MAX_BUF]="";    
char sSYSFS_USRLED_Path[MAX_BUF]="";
int iSYSFS_Write_Result=0;
int iSYSFS_Trigger_Result=0;

// Initialize USR LED State
eUSRLED_STATE iUSRLED_State;

// Initialize Error
eError_No iError_No = Error_None;
// Initialize Error Level
eError_Level iError_Level = Error_Level_OK;
// Initialize Debug Output Level
eDebugLevel iDebug_Level = Debug_None;


/****************************************/
// Function: Remove Standard Trigger
/****************************************/
int iBBB_USRLED_TriggerOff()
{
    sprintf(sSYSFS_USRLED_Trigger,"%s/trigger",sSYSFS_USRLED_Path);
    // Validate Path - Check USR LED Trigger Concatenation
    if (iDebug_Level >=Debug_Level_2)  { printf("USRLED Msg: USRLED SYSFS Path: %s\n",sSYSFS_USRLED_Trigger); }
    
    if((iFILE_BBB_USRLED_Handle = fopen(sSYSFS_USRLED_Trigger, "r+")) != NULL)
    {
        if (fwrite("none", sizeof("none"), 1, iFILE_BBB_USRLED_Handle)<=0)
        {
            // Error Handling
            if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed to Write to USRLED SYSFS Trigger (None) File - Check Connection to BBB\n"); }
            // Set Error Number
            iError_No = Error_No_SYSFSWrite;
            // Set Error Level
            iError_Level = Error_Level_Critical;
        }
        fclose(iFILE_BBB_USRLED_Handle);
    }
    else
    {
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed Find/Open USRLED SYSFS Trigger (None) File  - Check USRLED Number/Connection to BBB\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSOpen;
        // Set Error Level
        iError_Level = Error_Level_Critical;        
    }
    // printf("iError_No= %i Error_None= %i\n",iError_No,Error_None);
    // Return Error Code
    if (iError_No!=Error_None)
    {   // Return Otuput Error Level
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: - Error Return From ""iBBB_USRLED_TriggerOff()"" Function\n");}       
        // Return Error Code
        return -1;

    }
    else
    {
        return 0;
    }

}

/****************************************/
// Function: Re-Apply Standard Trigger   / 
/****************************************/
int iBBB_USRLED_TriggerOn()
{
    sprintf(sSYSFS_USRLED_Trigger,"%s/trigger",sSYSFS_USRLED_Path);
    // Validate Path - Check USR LED Trigger Concatenation
    if (iDebug_Level >=Debug_Level_2)  { printf("USRLED Msg: USRLED SYSFS Path - Trigger: %s\n",sSYSFS_USRLED_Trigger); }
    
    if((iFILE_BBB_USRLED_Handle = fopen(sSYSFS_USRLED_Trigger, "r+")) != NULL)
    {
        // Re-Apply Trigger Corresponding to USR LED
        switch(prmUSRLED_No[0])
        {
            case BBB_USRLED0:
                iSYSFS_Write_Result=fwrite("heartbeat", sizeof("heartbeat"), 1, iFILE_BBB_USRLED_Handle);
                if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Msg: Re-Applying ""heartbeat"" Trigger \n"); }
                break;
            case BBB_USRLED1:
                iSYSFS_Write_Result=fwrite("mmc0", sizeof("mmc0"), 1, iFILE_BBB_USRLED_Handle);
                if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Msg: Re-Applying ""mmc0"" Trigger \n"); }
                break;
            case BBB_USRLED2:
                iSYSFS_Write_Result=fwrite("cpu0", sizeof("cpu0"), 1, iFILE_BBB_USRLED_Handle);
                if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Msg: Re-Applying ""cpu0"" Trigger \n"); }                
                break;
            case BBB_USRLED3:
                iSYSFS_Write_Result=fwrite("mmc1", sizeof("mmc1"), 1, iFILE_BBB_USRLED_Handle);
                if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Msg: Re-Applying ""mmc1"" Trigger \n"); }
                break;
            default:
                // Do Nothing
                break;
        }
        if (iSYSFS_Write_Result<=0)
        {
            // Error Handling
            if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed to Write to USRLED SYSFS Trigger (On) File - Check Connection to BBB\n"); }
            // Set Error Number
            iError_No = Error_No_SYSFSWrite;
            // Set Error Level
            iError_Level = Error_Level_Critical;           
        }
        // Close File
        fclose(iFILE_BBB_USRLED_Handle);
        
    }
    else
    {
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed Find/Write to USRLED SYSFS Trigger(Reset) File - Check USRLED Number/Connection to BBB\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSOpen;
        // Set Error Level
        iError_Level = Error_Level_Critical;
    }
    // Return Error Code
    if (iError_No!=Error_None)
    {   // Return Otuput Error Level
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: - Error Return From ""iBBB_USRLED_TriggerOn()"" Function\n");}       
        // Return Error Code
        return -1;
        
    }
    else
    {
        return 0;
    }
}

/****************************************/
/****************************************/
// Main Program Start
/****************************************/
/****************************************/

if (inUSRLED_Enable[0]==true)
{
    if (xD[1]!=(double)inUSRLED_On_Trigger[0])
    {
        
        // Set Debug Level - Read Parameter Data -Debug Level
        iDebug_Level = iSet_Debug_Level(prmDebug_InfoLevel[0]);
        
        // Start Line
        if (iDebug_Level >=Debug_Level_0){printf("**** Start of USRLED Control S-Function Block Execution **** \n");}
        
        
        // Create SYSFS Path for Specified USR LED
        sprintf(sSYSFS_USRLED_Path,"%s%d",sSYSFS_USRLED,prmUSRLED_No[0]-1);
        
        // Validate Path - Check USR LED Concatenation
        if (iDebug_Level >=Debug_Level_2)  { printf("USRLED Msg: USRLED SYSFS Path: %s\n",sSYSFS_USRLED_Path);}
        
        /* Check Initialization */
        if (xD[0]==0)
        {
            
            // printf("iBBB_USRLED_TriggerOff: %i %f\n",iBBB_USRLED_TriggerOff(),iBBB_USRLED_TriggerOff());
            //iError_Level = Error_Level_Critical;
            // Remove All Triggers
            iSYSFS_Trigger_Result=iBBB_USRLED_TriggerOff();
            printf("iSYSFS_Trigger_Result: %i %f\n",iSYSFS_Trigger_Result,iSYSFS_Trigger_Result);
            if ((iSYSFS_Trigger_Result)<=-1)
            {
                // Error Handling
                if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed to Remove Standard Trigger - Check Connection to BBB\n"); }
                // Set Error Number
                iError_No = Error_No_USRLED_TriggerOff;
                // Set Error Level
                iError_Level = Error_Level_Critical;
            }
        }
        
        // Confirm No Errors
        if (iError_Level==Error_None)
        {
            // Create SYSFS Path for Specified USR LED
            sprintf(sSYSFS_USRLED_Brightness,"%s/brightness",sSYSFS_USRLED_Path);
            
            // Validate Path - Check USR LED Concatenation
            if (iDebug_Level >=Debug_Level_2)  { printf("USRLED Msg: USRLED SYSFS Path - Brightness: %s\n",sSYSFS_USRLED_Brightness);}
            
            /*Turn Off/On USR LED */
            if (inUSRLED_On_Trigger[0]==true) /* && In_Leds_On[0]==0) */
            {
                /* Turn On USR LED */
                if((iFILE_BBB_USRLED_Handle = fopen(sSYSFS_USRLED_Brightness, "r+")) != NULL)
                {
                    if (fwrite("1", sizeof(char), 1, iFILE_BBB_USRLED_Handle)<=0)
                    {
                        // Error Handling
                        if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed to Write to USRLED SYSFS Brightness (On) File - Check Connection to BBB\n"); }
                        // Set Error Number
                        iError_No = Error_No_SYSFSWrite;
                        // Set Error Level
                        iError_Level = Error_Level_Critical;
                    }
                    fclose(iFILE_BBB_USRLED_Handle);
                    // Set Led State
                    iUSRLED_State=BBB_USRLED_ON;
                }
                else
                {
                    // Error Handling
                    if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed Find/Open/Write to USRLED SYSFS Brightness File (On) - Check Connection to BBB\n"); }
                    // Set Error Number
                    iError_No = Error_No_SYSFSOpen;
                    // Set Error Level
                    iError_Level = Error_Level_Critical;
                }
            }
            else
            {
                /* Turn Off USR LED */
                if((iFILE_BBB_USRLED_Handle = fopen(sSYSFS_USRLED_Brightness, "r+")) != NULL)
                {
                    if (fwrite("0", sizeof(char), 1, iFILE_BBB_USRLED_Handle)<=0)
                    {
                        // Error Handling
                        if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed to Write to USRLED SYSFS Brightness (Off) File - Check Connection to BBB\n"); }
                        // Set Error Number
                        iError_No = Error_No_SYSFSWrite;
                        // Set Error Level
                        iError_Level = Error_Level_Critical;
                    }
                    fclose(iFILE_BBB_USRLED_Handle);
                    // Set Led State
                    iUSRLED_State=BBB_USRLED_OFF;
                }
                else
                {
                    // Error Handling
                    if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed Find/Open/Write to USRLED SYSFS Brightness (Off) File - Check Connection to BBB\n"); }
                    // Set Error Number
                    iError_No = Error_No_SYSFSOpen;
                    // Set Error Level
                    iError_Level = Error_Level_Critical;
                }
                
            }
        }
        // Check For Critical Errors and Stop Simulation
        if ((iError_No!=0)&&(iError_Level==Error_Level_Critical))
        {
            
            // Stop Simulation If Critical Error
            if (iDebug_Level >=Debug_Level_0) {printf("USRLED Msg: Critical Error Detected; Simulation Stopping! \nError No: %i Error Level: %i\n",iError_No, iError_Level);}
            
            // Output Error Message:
            if (iDebug_Level >=Debug_Level_0) {printf("USRLED Error Details: %s",sSYSFSReadWrite_ErrMessage(iError_No));}
            
            
            // Stop Simulation
            outSimStop[0]=true;
        }
        else
        {
            // Output USRLED State
            outUSRLED_State[0]=iUSRLED_State;
            
            
            // Carry on
            outSimStop[0]=false;
        }

    }
    // Print Gap
    if ((iDebug_Level >=Debug_Level_0)){printf("\n");}
}
else
{
    // Reset USR LED
    if  (xD[0]==1)
    {
     
        // Set Debug Level - Read Parameter Data -Debug Level
        iDebug_Level = iSet_Debug_Level(prmDebug_InfoLevel[0]);

        // Start Line
        if (iDebug_Level >=Debug_Level_0){printf("**** Start of USRLED Control S-Function Block Execution **** \n");}

        // Set SYSFS Path for Specified USR LED
        sprintf(sSYSFS_USRLED_Path,"%s%d",sSYSFS_USRLED,prmUSRLED_No[0]-1);
    
        // Validate Path - Check USR LED Concatenation
        if (iDebug_Level >=Debug_Level_2)  { printf("USRLED Msg: USRLED SYSFS Path: %s\n",sSYSFS_USRLED_Path);}

        // Create SYSFS Path for Specified USR LED
        sprintf(sSYSFS_USRLED_Brightness,"%s/brightness",sSYSFS_USRLED_Path);
        
        // Validate Path - Check USR LED Concatenation
        if (iDebug_Level >=Debug_Level_2)  { printf("USRLED Msg: USRLED SYSFS Path - Brightness: %s\n",sSYSFS_USRLED_Brightness);}
        
        /* Turn Off USR LED */
        if((iFILE_BBB_USRLED_Handle = fopen(sSYSFS_USRLED_Brightness, "r+")) != NULL)
        {
            if (fwrite("0", sizeof(char), 1, iFILE_BBB_USRLED_Handle)<=0)
            {
                // Error Handling
                if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed to Write to USRLED SYSFS Brightness (Off) File - Check Connection to BBB\n"); }
                // Set Error Number
                iError_No = Error_No_SYSFSWrite;
                // Set Error Level
                iError_Level = Error_Level_Critical;
            }
            fclose(iFILE_BBB_USRLED_Handle);
            // Set Led State
            iUSRLED_State=BBB_USRLED_OFF;
        }
        else
        {
            // Error Handling
            if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed Find/Open/Write to USRLED SYSFS Brightness (Off) File - Check Connection to BBB\n"); }
            // Set Error Number
            iError_No = Error_No_SYSFSOpen;
            // Set Error Level
            iError_Level = Error_Level_Critical;
        }

        if (iError_Level != Error_Level_Critical)
        {
            // Reset USR LED Standard Triggers
            if (iBBB_USRLED_TriggerOn()<0)
            {
                // Error Handling
                if (iDebug_Level >=Debug_Level_1)  { printf("USRLED Error: Failed to Re-Apply Standard Trigger - Check Connection to BBB\n"); }
                // Set Error Number
                iError_No = Error_No_USRLED_TriggerOn;
                // Set Error Level
                iError_Level = Error_Level_Critical;
            }
        }
    }
     // Check For Critical Errors and Stop Simulation
    if ((iError_No!=0)&&(iError_Level==Error_Level_Critical))
    {
        
        // Stop Simulation If Critical Error
        if (iDebug_Level >=Debug_Level_0) {printf("USRLED Msg: Critical Error Detected; Simulation Stopping! \nError No: %i Error Level: %i\n",iError_No, iError_Level);}
        
        // Output Error Message:
        if (iDebug_Level >=Debug_Level_0) {printf("USRLED Error Details: %s",sSYSFSReadWrite_ErrMessage(iError_No));}
        
        
        // Stop Simulation
        outSimStop[0]=true;
    }
    else
    {
        // Output USRLED State
        outUSRLED_State[0]=iUSRLED_State;
        
        
        // Carry on
        outSimStop[0]=false;
    }
    // Print Gap
    if ((iDebug_Level >=Debug_Level_0)){printf("\n");}
}


#else
# endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  * Updates function
  *
  */
void BBB_Driver_USRLED_Update_wrapper(const real_T *inUSRLED_Enable,
                          const boolean_T *inUSRLED_On_Trigger,
                          const boolean_T *outUSRLED_State,
                          const boolean_T *outSimStop ,
                          real_T *xD, 
                          const uint8_T  *prmUSRLED_No,  const int_T  p_width0,
                           const uint8_T *prmDebug_InfoLevel, const int_T  p_width1)
{
  /* %%%-SFUNWIZ_wrapper_Update_Changes_BEGIN --- EDIT HERE TO _END */
# ifndef MATLAB_MEX_FILE

// Notes On Discrete States
// xD[0]: First Scan
// xD[1]: Output State Memorization
// Initialize Debug Output Level

eDebugLevel iDebug_Level = Debug_None; 

// Check Debug Level - Read Parameter Data -Debug Level
iDebug_Level = iSet_Debug_Level(prmDebug_InfoLevel[0]);

// Record Output State
xD[1]=outUSRLED_State[0];
    
if ((xD[0]!=1) && (inUSRLED_Enable[0]==true))
{
    // Set First Scan Bit
    xD[0]=1;
    if ((iDebug_Level >=Debug_Level_0)){printf("USRLED Msg: First Scan Bit Set\n");}
    // Print Gap
    if ((iDebug_Level >=Debug_Level_0)){printf("\n");}

}
else if ((xD[0]==1) && (inUSRLED_Enable[0]==false))
{
    // Reset First Scan Bit
    xD[0]=0;
    if ((iDebug_Level >=Debug_Level_0)){printf("USRLED Msg: First Scan Bit ReSet\n");}
    // Print Gap
    if ((iDebug_Level >=Debug_Level_0)){printf("\n");}
}
// Print Standard Output
if ((iDebug_Level >=Debug_Level_2)&&(inUSRLED_Enable[0]==true)){printf("USRLED Msg: Waiting For Input Change\n");}

// Print Gap
// if ((iDebug_Level >=Debug_Level_0)&&(inUSRLED_Enable[0]==true) && (xD[1]!=(double)inUSRLED_On_Trigger[0])){printf("\n");}

#endif

//     /* Only Execute On Target*/
//     # ifndef MATLAB_MEX_FILE
//    
//     static FILE *LEDHandle1 = NULL;
//     const char *LED_00_Trigger="/sys/class/leds/beaglebone:green:usr3/trigger";
//    
//     
//     if((LEDHandle1 = fopen(LED_00_Trigger, "r+")) != NULL)
//         {
//  		fwrite("none", sizeof(char), 4, LEDHandle1);
//  		fclose(LEDHandle1);
//         }
//     
//     # endif
//     
//     /* Update Discrete Bit */
//     xD[0]=1;
/* %%%-SFUNWIZ_wrapper_Update_Changes_END --- EDIT HERE TO _BEGIN */
}
