/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sun Dec 14 05:04:47 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include <stdio.h>
#include <stddef.h>
#include <time.h>

# ifdef MATLAB_MEX_FILE
	#include <mex.h>
	#include <simstruc.h>
# endif


#define dBBB_ADC_Op_Voltage_3V6 3.6
#define dBBB_ADC_Op_Voltage_3V33 3.33
#define dBBB_ADC_Op_Voltage_3V0 3.0
#define dBBB_ADC_Op_Voltage_2V0 2.0
#define iBBB_ADC_Sensitivity_3V6 360
#define iBBB_ADC_Sensitivity_3V33 333
#define iBBB_ADC_Sensitivity_3V0 300
#define iBBB_ADC_Sensitivity_2V0 195

float dBBB_ADC_Volt_Val_X_Global=0;
float dBBB_ADC_Volt_Val_Y_Global=0;
float dBBB_ADC_Volt_Val_Z_Global=0;

// Define Debug Levels
typedef enum 
{
       	Debug_None,
	Debug_Level_0, // Basic Debug Info Output
        Debug_Level_1, // + Critical Info Only
	Debug_Level_2, // + Diagnostics Info
	Debug_Level_3, // + Program Flow Info
	Debug_Level_4, // + Registry Data
	Debug_Level_5  // + TBD 
}eDebugLevel;


// Define Error Number
typedef enum 
{
    Error_None=0,
    Error_No_SYSFSOpen,
    Error_No_SYSFSSeek,
    Error_No_SYSFSScan, 
    Error_No_SYSFSClose,
    Error_No_ParamOutofRange
}eError_No;

// Initialize Error
// eError_No iError_No = Error_None;

// Define Error Severity Levels
typedef enum
{
    Error_Level_OK=0,
    Error_Level_Critical, // (Stop Simulation)
    Error_Level_Warning
}eError_Level;
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void BBB_Driver_Accelerometer_ADXL330_Outputs_wrapper(real_T *outX_Axis_Accel,
                          real_T *outY_Axis_Accel,
                          real_T *outZ_Axis_Accel,
                          boolean_T *outSimStop ,
			      const real_T  *xD,
                          const uint16_T  *prmAccel_Sensitivity, const int_T  p_width0, 
                          const boolean_T  *prmRunCalibration, const int_T  p_width1, 
                          const uint16_T  *prmDebug_InfoLevel, const int_T p_width2)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
// Define Output Data - Simulink

// Run Only on Target - BeagleBoneBlack */
# ifndef MATLAB_MEX_FILE

// Declare and Initialize Error
eError_No iError_No = Error_None;

// Declare and Initialize Error Level
eError_Level iError_Level = Error_Level_OK;

// Define File Sys Pointer - Note Code Will Use fopen vs. open
static FILE *fBBB_Handle_X = NULL;
static FILE *fBBB_Handle_Y = NULL;
static FILE *fBBB_Handle_Z = NULL;
const char *sBBB_ACC_AIN_X ="/sys/bus/platform/drivers/bone-iio-helper/helper.15/AIN0";
const char *sBBB_ACC_AIN_Y ="/sys/bus/platform/drivers/bone-iio-helper/helper.15/AIN1";
const char *sBBB_ACC_AIN_Z ="/sys/bus/platform/drivers/bone-iio-helper/helper.15/AIN2";

// Define Internal Variable Data
float dBBB_ADC_Volt_Val_X=0;
float dBBB_ADC_Volt_Val_Y=0;
float dBBB_ADC_Volt_Val_Z=0;
float dBBB_ACC_Val_X=0;
float dBBB_ACC_Val_Y=0;
float dBBB_ACC_Val_Z=0;
float const dBBB_ACC_Val_X_Nominal=1666+(-0.06006*333);
float const dBBB_ACC_Val_Y_Nominal=1666+(-1.234234*333);//+(-0.234234*333);
float const dBBB_ACC_Val_Z_Nominal=1666+((0.912013-1)*333);
float dBBB_ADC_Volt_CalibOffset_X=0;
float dBBB_ADC_Volt_CalibOffset_Y=0;
float dBBB_ADC_Volt_CalibOffset_Z=0;
float dBBB_ADC_Volt_Nominal_X=0;
float dBBB_ADC_Volt_Nominal_Y=0;
float dBBB_ADC_Volt_Nominal_Z=0;
float dBBB_ADC_Volt_Correction_X=0;
float dBBB_ADC_Volt_Correction_Y=0;
float dBBB_ADC_Volt_Correction_Z=0;
int iBBB_ADC_Sensitivity[5]={
    0,
    iBBB_ADC_Sensitivity_3V6,
    iBBB_ADC_Sensitivity_3V33,
    iBBB_ADC_Sensitivity_3V0,
    iBBB_ADC_Sensitivity_2V0};
     
        
float dBBB_ADC_OpVoltage[5]={
    0,
    dBBB_ADC_Op_Voltage_3V6,
    dBBB_ADC_Op_Voltage_3V33,
    dBBB_ADC_Op_Voltage_3V0,
    dBBB_ADC_Op_Voltage_2V0};
    
// Initialize Debug Output Level
eDebugLevel iDebug_Level = Debug_None;

/****************************************/
// Accelerometer Error Message Output 
/****************************************/
const char *sAccel_ErrMessage(eError_No iAccel_ErrNo)
{
    //Set Error Message Based on Error Number
    switch(iAccel_ErrNo)
    {     
       case  Error_None:
            return("No Error Active. System A-OK!\n");
            break;
        case  Error_No_SYSFSOpen: 
            return("Failed to Open I2C Bus\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device\n - Check Device Tree on BBB\n");
            break;
        case  Error_No_SYSFSSeek: 
            return("Failed to Open I2C Bus\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device\n - Check Device Tree on BBB\n");
            break;
        case Error_No_SYSFSScan:
            return("Failed to Communicate With Slave Device\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device Address\n - Check Device Tree on BBB\n");        
            break;            
        case Error_No_SYSFSClose:
            return("Failed to Set Buffer Read Range\n - Check Bus Number\n - Check SCL/SCA Lines\n" 
                   " - Check Device Address\n - Check Device Tree on BBB\n");            
            break;      
        case Error_No_ParamOutofRange:
            return("Parameter Out Of Range\n - Check Block Parameter Input Options\n");
            break;        
        default:
            // Error -Return Default 
            return("Error Code Not Recognized\n");
            break;
    }          
}

/****************************************/
/****************************************/
// Main Program Start
/****************************************/
/****************************************/

// Read Parameter Data -Debug Level
switch(prmDebug_InfoLevel[0])
{
    case  1:
        iDebug_Level=Debug_None;
        break;
    case  2:
        iDebug_Level=Debug_Level_0;
        break;
    case  3:
        iDebug_Level=Debug_Level_1;
        break;
    case  4:
        iDebug_Level=Debug_Level_2;
        break;
    case  5:
        iDebug_Level=Debug_Level_3;
        break;
    case  6:
        iDebug_Level=Debug_Level_4;
        break;
    case  7:
        iDebug_Level=Debug_Level_5;
        break;
    default:
        iDebug_Level=Debug_None;
        break;
}

// Start Line
if (iDebug_Level >=Debug_Level_0){printf("**** Start of GPIO Write S-Function Block Execution **** \n");} 

// Open Streams
fBBB_Handle_X = fopen(sBBB_ACC_AIN_X, "r");
fBBB_Handle_Y = fopen(sBBB_ACC_AIN_Y, "r");
fBBB_Handle_Z = fopen(sBBB_ACC_AIN_Z, "r");

// Confirm SYSFS IOStream Open
if ((fBBB_Handle_X==NULL) | (fBBB_Handle_Y==NULL) | (fBBB_Handle_Z==NULL))
{
    // Error Handling
    if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: Failed To Open I/O File Stream - Check ""cape-bone-iio"" Device Tree Active\n"); }
    // Set Error Number
    iError_No = Error_No_SYSFSOpen;
    // Set Error Level
    iError_Level = Error_Level_Critical;
    // Return Otuput Error Level
    // return -1;
}

// Ouput Program Flow
if (iDebug_Level >=Debug_Level_3) {printf("Accelerometer Msg: Program Flow State 1: Open SYSFS File I/O Stream\nError No: %i Error Level: %i\n",iError_No, iError_Level);}
   

// Write Read Raw Voltage Data
if (iError_No == Error_None)
{
    // Read X Accel
    if (fseek(fBBB_Handle_X, 0, SEEK_SET)!=0)
    {    
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fseek()"" Failed To Set Position Indicator in X-Axis I/O File Stream\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSSeek;
        // Set Error Level
        iError_Level = Error_Level_Critical;
    }    
    if (fscanf(fBBB_Handle_X, "%f", &dBBB_ADC_Volt_Val_X)!=1)
    {    
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fscan()"" Failed To Read Data From X-Axis I/O File Stream\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSScan;
        // Set Error Level
        iError_Level = Error_Level_Critical;
    } 
    else
    {
        // Record Voltage Data in Global Variable
        dBBB_ADC_Volt_Val_X_Global=dBBB_ADC_Volt_Val_X;
    }
    
    // Read Y Accel
    if (fseek(fBBB_Handle_Y, 0, SEEK_SET)!=0)
    {    
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fseek()"" Failed To Set Position Indicator in Y-Axis I/O File Stream\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSSeek;
        // Set Error Level
        iError_Level = Error_Level_Critical;
    }    
    if (fscanf(fBBB_Handle_Y, "%f", &dBBB_ADC_Volt_Val_Y)!=1)
    {    
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fscan()"" Failed To Read Data From Y-Axis I/O File Stream\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSScan;
        // Set Error Level
        iError_Level = Error_Level_Critical;
    }     
    else
    {
        // Record Voltage Data in Global Variable
        dBBB_ADC_Volt_Val_Y_Global=dBBB_ADC_Volt_Val_Y;
    }
    
    // Read Z Accel
    if (fseek(fBBB_Handle_Z, 0, SEEK_SET)!=0)
    {    
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fseek()"" Failed To Set Position Indicator in Z-Axis I/O File Stream\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSSeek;
        // Set Error Level
        iError_Level = Error_Level_Critical;
    }    
    if (fscanf(fBBB_Handle_Z, "%f", &dBBB_ADC_Volt_Val_Z)!=1)
    {    
        // Error Handling
        if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fscan()"" Failed To Read Data From Z-Axis I/O File Stream\n"); }
        // Set Error Number
        iError_No = Error_No_SYSFSScan;
        // Set Error Level
        iError_Level = Error_Level_Critical;
    }
    else
    {
        // Record Voltage Data in Global Variable
        dBBB_ADC_Volt_Val_Z_Global=dBBB_ADC_Volt_Val_Z;
    }    
}

// Ouput Program Flow
if (iDebug_Level >=Debug_Level_3) {printf("Accelerometer Msg: Program Flow State 2: Seek & Scan Data From File I/O Stream\nError No: %i Error Level: %i\n",iError_No, iError_Level);}

// Voltage Calibration 
if ((prmRunCalibration[0]==true) && (xD[0]==1))
{

    
    // Check Sensitivity setting    
    switch(prmAccel_Sensitivity[0])
    {
               
        case  1: // 3.6V
            dBBB_ADC_Volt_Correction_X=(1000*dBBB_ADC_Op_Voltage_3V6/2)-2*xD[3]; 
            dBBB_ADC_Volt_Correction_Y=(1000*dBBB_ADC_Op_Voltage_3V6/2)-2*xD[4];
            dBBB_ADC_Volt_Correction_Z=(1000*(dBBB_ADC_Op_Voltage_3V6/2)+iBBB_ADC_Sensitivity_3V6)-2*xD[5];          
            break;
        case  2: // 3.3V
            dBBB_ADC_Volt_Correction_X=(1000*dBBB_ADC_Op_Voltage_3V33/2)-2*xD[3]; 
            dBBB_ADC_Volt_Correction_Y=(1000*dBBB_ADC_Op_Voltage_3V33/2)-2*xD[4];
            dBBB_ADC_Volt_Correction_Z=(1000*(dBBB_ADC_Op_Voltage_3V33/2)+iBBB_ADC_Sensitivity_3V33)-2*xD[5];  
            break;           
        case  3: // 3.0V
            dBBB_ADC_Volt_Correction_X=(1000*dBBB_ADC_Op_Voltage_3V0/2)-2*xD[3]; 
            dBBB_ADC_Volt_Correction_Y=(1000*dBBB_ADC_Op_Voltage_3V0/2)-2*xD[4];
            dBBB_ADC_Volt_Correction_Z=(1000*(dBBB_ADC_Op_Voltage_3V0/2)+iBBB_ADC_Sensitivity_3V0)-2*xD[5];  
            break;           
        case  4: // 2.0V
            dBBB_ADC_Volt_Correction_X=(1000*dBBB_ADC_Op_Voltage_2V0/2)-2*xD[3]; 
            dBBB_ADC_Volt_Correction_Y=(1000*dBBB_ADC_Op_Voltage_2V0/2)-2*xD[4];
            dBBB_ADC_Volt_Correction_Z=(1000*(dBBB_ADC_Op_Voltage_2V0/2)+iBBB_ADC_Sensitivity_2V0)-2*xD[5];  
            break;
        default: 
            break;
            
    }
}



// Convert Voltage To Acceleration (in g) Depending on Sensitivity Setting
if (iError_No == Error_None)
{
    // Convert Voltage To Acceleration (in g)
    dBBB_ACC_Val_X=(((2*dBBB_ADC_Volt_Val_X)+dBBB_ADC_Volt_Correction_X)-(1000*dBBB_ADC_OpVoltage[prmAccel_Sensitivity[0]]/2))/iBBB_ADC_Sensitivity[prmAccel_Sensitivity[0]];
    dBBB_ACC_Val_Y=(((2*dBBB_ADC_Volt_Val_Y)+dBBB_ADC_Volt_Correction_Y)-(1000*dBBB_ADC_OpVoltage[prmAccel_Sensitivity[0]]/2))/iBBB_ADC_Sensitivity[prmAccel_Sensitivity[0]];
    dBBB_ACC_Val_Z=(((2*dBBB_ADC_Volt_Val_Z)+dBBB_ADC_Volt_Correction_Z)-(1000*dBBB_ADC_OpVoltage[prmAccel_Sensitivity[0]]/2))/iBBB_ADC_Sensitivity[prmAccel_Sensitivity[0]];
    
}

// Ouput Program Calibration Data
if (iDebug_Level >=Debug_Level_3) {printf("Accelerometer Msg: Avrg. Recorded Voltage Reading X: %.2f, Y: %.2f Z: %.2f \n",xD[3],xD[4],xD[5]);}

// Ouput Program Calibration Data
if (iDebug_Level >=Debug_Level_3) {printf("Accelerometer Msg: Voltage Correcton Data: X: %.2f, Y: %.2f Z: %.2f \n",dBBB_ADC_Volt_Correction_X,dBBB_ADC_Volt_Correction_Y,dBBB_ADC_Volt_Correction_Z);}

// Ouput Program Calibration Data
if (iDebug_Level >=Debug_Level_3) {printf("Accelerometer Msg: Voltage Sensitivity Level (mV/g): %i \n",iBBB_ADC_Sensitivity[prmAccel_Sensitivity[0]]);}


// Ouput Program Flow
if (iDebug_Level >=Debug_Level_3) {printf("Accelerometer Msg: Program Flow State 3: Convert Voltage Data to Acceleration \nError No: %i Error Level: %i\n",iError_No, iError_Level);}

// Close File on Exit
if (fclose(fBBB_Handle_X)!=0)
{
    // Error Handling
    if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fclose()"" Failed To Properly Close Data From X-Axis I/O File Stream\n"); }
    // Set Error Number
    iError_No = Error_No_SYSFSClose;
    // Set Error Level
    iError_Level = Error_Level_Critical;
}

// Close File on Exit
if (fclose(fBBB_Handle_Y)!=0)
{
    // Error Handling
    if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fclose()"" Failed To Properly Close Data From Y-Axis I/O File Stream\n"); }
    // Set Error Number
    iError_No = Error_No_SYSFSClose;
    // Set Error Level
    iError_Level = Error_Level_Critical;
}

// Close File on Exit
if (fclose(fBBB_Handle_Z)!=0)
{
    // Error Handling
    if (iDebug_Level >=Debug_Level_1)  { printf("Accelerometer Error: ""fclose()"" Failed To Properly Close Data From Z-Axis I/O File Stream\n"); }
    // Set Error Number
    iError_No = Error_No_SYSFSClose;
    // Set Error Level
    iError_Level = Error_Level_Critical;
}

// Ouput Program Flow
if (iDebug_Level >=Debug_Level_3) {printf("Accelerometer Msg: Program Flow State 4: Close SYSFS File I/O Stream\nError No: %i Error Level: %i\n",iError_No, iError_Level);}


// Print Acceleration Data
if (iDebug_Level >=Debug_Level_0)  { printf("Accel: X: %f  Y: %f  Z: %f\n",dBBB_ACC_Val_X,dBBB_ACC_Val_Y,dBBB_ACC_Val_Z);}
// Print Voltage Data
if (iDebug_Level >=Debug_Level_1)  { printf("Voltage: X: %f  Y: %f  Z: %f\n",dBBB_ADC_Volt_Val_X,dBBB_ADC_Volt_Val_Y,dBBB_ADC_Volt_Val_Z);}

// Check For Critical Errors and Stop Simulation
if (((iError_No!=0)&&(iError_Level==Error_Level_Critical))) //|| (xD[0]==true)) 
{
    
    // Stop Simulation If Critical Error
    if (iDebug_Level >=Debug_Level_0) {printf("Accelerometer Msg: Critical Error Detected; Simulation Stopping! \nError No: %i Error Level: %i\n",iError_No, iError_Level);}
    
    // Output Error Message:
    if (iDebug_Level >=Debug_Level_0) {printf("Accelerometer Error Details: %s",sAccel_ErrMessage(iError_No));}
    
    
    // Stop Simulation
    outSimStop[0]=true;
}
else
{
    // Carry on
    outSimStop[0]=false;

    // Transfer Data to Outputs!
    outX_Axis_Accel[0]=dBBB_ACC_Val_X;
    outY_Axis_Accel[0]=dBBB_ACC_Val_Y;
    outZ_Axis_Accel[0]=dBBB_ACC_Val_Z;
    
    // Print Lint Space:
    if (iDebug_Level >=Debug_Level_0) {printf("\n");}
    
}

# else


# endif
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  * Updates function
  *
  */
void BBB_Driver_Accelerometer_ADXL330_Update_wrapper(const real_T *outX_Axis_Accel,
                          const real_T *outY_Axis_Accel,
                          const real_T *outZ_Axis_Accel,
                          const boolean_T *outSimStop ,
                          real_T *xD, 
                          const uint16_T  *prmAccel_Sensitivity,  const int_T  p_width0,
                          const boolean_T  *prmRunCalibration,  const int_T  p_width1,
                           const uint16_T *prmDebug_InfoLevel, const int_T  p_width2)
{
  /* %%%-SFUNWIZ_wrapper_Update_Changes_BEGIN --- EDIT HERE TO _END */
// Run Only on Target - BeagleBoneBlack */
# ifndef MATLAB_MEX_FILE


// Parameter Definition
// xD[0]= First Scan / Calibration Complete / Init: 0
// xD[1]= Calibration Sample Counter / Init: 0
// xD[2]= Calibration Sample Quantity / Init: 10
// xD[3]= X Axis Voltage Total Sum / Init: 0
// xD[4]= Y Axis Voltage Total Sum / Init: 0
// xD[5]= Z Axis Voltage Total Sum / Init: 0


// Check & Execute Calibraiton Routine 
if ((prmRunCalibration[0]==true) && (xD[0]==0))
{
   if (xD[1]<xD[2])
   {
      // Update X Voltage Sum
      xD[3]=xD[3]+dBBB_ADC_Volt_Val_X_Global; 
      // Update Y Voltage Sum
      xD[4]=xD[4]+dBBB_ADC_Volt_Val_Y_Global;       
      // Update Z Voltage Sum
      xD[5]=xD[5]+dBBB_ADC_Volt_Val_Z_Global; 
      
      // Increment Sample Counter
      xD[1]=xD[1]+1;
   }
   else
   {
     // Voltage Sample Sum Completed Calculate Average
     xD[3]=xD[3]/xD[2]; // X Voltage
     xD[4]=xD[4]/xD[2]; // Y Voltage     
     xD[5]=xD[5]/xD[2]; // Z Voltage     

     // Set Calibration Flag Complete/ First Scan Bit
      xD[0]=1;
   }
}
else
{    
    if (xD[0]==0)
    {
    // Set First Scan Bit
    xD[0]=1;
    }
}


// Print Space Line
//printf("/n");






# endif
/* %%%-SFUNWIZ_wrapper_Update_Changes_END --- EDIT HERE TO _BEGIN */
}
